Main/urls.py
from django.urls import path, re_path
from . import views
from Main.views import *

app_name = 'main'
urlpatterns = [
    path('Stock/', views.stockMain, name="stock"),
    path('Stock/Inquiry/', views.readItems, name="readItems"),
    path('Stock/Add/Items/', views.addItems, name="addItems"),
    path('Stock/<int:pk>/Delete/', StockDelete.as_view(), name='deleteItem'),
    path('Stock/<int:pk>/Edit/', StockUpdate.as_view(), name='updateItem'),
    path('Stock/<pk>/Update/', views.ajaxStockUpdate, name="ajaxStockUpdate"),
    path('Order/Inquiry/', views.readOrders, name='readOrders'),
    path('Order/Add/Items/', views.addOrders, name='addOrders'),
    path('Order/<int:pk>/Delete/', OrderDelete.as_view(), name='deleteOrders'),
    path('Order/<int:pk>/Edit/', OrderUpdate.as_view(), name="updateOrder"),
    path('Order/<pk>/Incoming/', views.ajaxIncomingOrder, name="incomingOrder"),
    path('Stock/History/<page>', views.getStockHistory, name="getStockHistory"),

    path('Sell/', views.sell, name="sell"),
    path('Sell/Admin/', views.sellAdmin, name="sellAdmin"),
    path('Sell/Menu/Register/', views.sell_registerMenu, name="sell_registerMenu"),
    path('Sell/<int:pk>/Delete/', SellDelete.as_view(), name="sell_delete"),
    path('Sell/<int:pk>/Update/', SellUpdate.as_view(), name="sell_update"),

    path('Order/State/', views.orderState, name='orderState'),
    path('Order/past/', PastOrder.as_view(), name='pastOrder'),
    path('ajax/Order/<pk>/Done/', orderDone.as_view(), name='orderDone'),
    path('ajax/Order/<pk>/Cancel/', orderCancel.as_view(), name='orderCancel'),

    #인사관리
    path('Human', views.Human, name='Human'), #인사관리 메인페이지
    path('Human/Employee/Enrollment', views.EmpEnrollment, name='EmpEnrollment'), #사원등록
    path('Human/Employee/Inquire', views.EmpInquire, name='EmpInquire'), #사원조회
    path('Human/Employee/Delete/<int:pk>', views.EmpDelete, name='EmpDelete'), #사원삭제
    path('Human/Employee/Save/<int:pk>', views.EmpSave, name='EmpSave'), #사원변경
    path('Human/Education/Enrollment', views.EduEnrollment, name='EduEnrollment'), #교육등록
    path('Human/Education/Inquire', views.EduInquire, name='EduInquire'), #교육조회
    path('Human/Education/Save/<int:pk>', views.EduSave, name='EduSave'), #교육변경
    path('Human/Education/Delete/<int:pk>', views.EduDelete, name='EduDelete'), #교육삭제
    path('Human/Work/Enrollment', views.WorkEnrollment, name='WorkEnrollment'), #근무등록
    path('Human/Work/Inquire', views.WorkInquire, name='WorkInquire'), #근무조회
    path('Human/Work/Save/<int:pk>', views.WorkSave, name='WorkSave'), #근무변경
    path('Human/Work/Delete/<int:pk>', views.WorkDelete, name='WorkDelete'), #근무삭제
    path('Human/Payroll_Calculator', views.PayCal, name='PayCal'), #급여계산기
    path('Human/Pay/Enrollment', views.PayEnrollment, name='PayEnrollment'), #급여등록
    path('Human/Pay/Inquire', views.PayInquire, name='PayInquire'), #급여조회
    path('Human/Pay/Save/<int:pk>', views.PaySave, name='PaySave'), #급여변경
    path('Human/Pay/Delete/<int:pk>', views.PayDelete, name='PayDelete'), #급여삭제
    path('Human/Hire/Enrollment', views.HireEnrollment, name='HireEnrollment'), #채용등록
    path('Human/Hire/Inquire', views.HireInquire, name='HireInquire'), #채용조회
    path('Human/Hire/Detail/<int:pk>', views.HireDetail, name='HireDetail'), #채용세부조회
    path('Hire/Main', views.HireMian, name='HireMain'), #채용메인페이지
    path('Hire/Main/Sign/<int:pk>', views.HireSign, name='HireSign'), #이력서 등록

    # 매출 관리
    path('Profit/', ProfitMain.as_view(), name="profit-main"),
    path('Profit/Search/', ProfitSearch.as_view(), name="profit-search"),
    path('Profit/add/', ProfitAdd.as_view(), name="profit-add"),
    path('Spending/add/', SpendingAdd.as_view(), name="spending-add"),
    path('Spending/', SpendingMain.as_view(), name="spending-main"),
    path('Spending/Search/', SpendingSearch.as_view(), name="spending-search"),
    path('Analysis/', Analysis.as_view(), name="analysis"),

    # Api
    path('Menu/list/', MenuApi.as_view(), name='menu-list'),
    path('Menu/list2/', MenuRestApi.as_view({'get' : 'list', }), name='menu-list2'),
    path('Order/create/', OrderApi.as_view(), name='menu-order')
]

RMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls', namespace='main')),
    path('Ordering/', include('Order.urls')),
    path('Counter/', include('Counter.urls', namespace='counter'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/views.py
from django.shortcuts import render, HttpResponse, Http404, render_to_response, redirect
from .models import *
from django.forms.models import modelform_factory
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic import ListView
from django.views import View
import json
from django.core import serializers
from django.db.models import F, Sum, Count

# -------------- 재고 부분 ------------------#
# Main
def stockMain(request):
    return render(request, 'Main/Stock/main.html')

# 재고 조회
def readItems(request):
    try:
        Stocks = Stock.objects.all()
    except Exception as e:
        Stocks = None

    return render(request, 'Main/Stock/Stock_read_items.html', {
        'Stocks' : Stocks
    })

# 재고 등록
def addItems(request):
    if request.method == 'POST':
        s_name = request.POST.get('name')
        s_count = request.POST.get('number')
        s_unit = request.POST.get('unit')
        s_incoming_at = request.POST.get('date')
        s_caution_num = request.POST.get('alter_number')
        s_expire_at = request.POST.get('expire_date')

        Stock.objects.create(
            s_name = s_name,
            s_count = int(s_count),
            s_unit = s_unit,
            s_incoming_at = s_incoming_at,
            s_caution_num = s_caution_num,
            s_expire_at = s_expire_at
        )
        print("재고 생성 완료")
        return redirect('/Stock/Inquiry/', {
            'Stocks' : Stock.objects.all(),
        })

    return render(request, 'Main/Stock/Stock_add_item.html')

# 재고 수정
class StockUpdate(UpdateView):
    model = Stock
    fields = ['s_name', 's_count', 's_unit', 's_incoming_at', 's_caution_num',
                's_expire_at']
    success_url = '/Stock/Inquiry/'
    template_name = 'Main/Stock/Stock_update_item.html'
    
    def get_initial(self):
        initial = super(StockUpdate, self).get_initial()
        return initial

# 재고 소비 및 충당
def ajaxStockUpdate(request, pk):
    message = ""
    m_count = request.POST.get("change_value")
    type_ = request.POST.get("type")
    data = dict()
    try:
        stock = Stock.objects.get(id=pk)
        if type_ == '0':
            stock.s_count =stock.s_count+float(m_count)
        else:
            stock.s_count =stock.s_count-float(m_count)

        if not stock.stock_checking():
            stock.s_status = False
        else:
            stock.s_status = True

        stock.save(update_fields=['s_count', 's_status'])
        message = "성공적으로 변경되었습니다."
        data['count'] = str(stock.s_count) + stock.s_unit
    except Exception as e:
        message = "처리 도중 오류가 생겼습니다."

    data['message'] = message
    return HttpResponse(json.dumps(data), content_type='application/json')

# 재고 삭제
class StockDelete(DeleteView):
    model = Stock
    success_url = '/Stock/Inquiry/'
    template_name = 'Main/Stock/Stock_read_items.html'

# 이력 조회
def getStockHistory(request, page):
    bar_size = 5
    offset = 10
    page = int(page)
    datas = Stocklog.objects.all().order_by('-sl_created_at')
    return render(request, 'Main/Stock/stock_read_history.html', {
        'historys' : datas[(int(page)-1)*offset:int(page)*offset],
        'page' : page,
        'page_start_point' : (page-1)//bar_size*bar_size,
        'MAX_SIZE' : len(datas)//offset,
        'PAGE_SIZE' : bar_size
    })

# -------------- 발주 부분 ------------------#
# 발주 등록
def addOrders(request):
    if request.method == 'POST':
        o_name = request.POST.get('name')
        o_number = request.POST.get('number')
        o_date = request.POST.get('date')
        o_unit = request.POST.get('unit')
        o_target = request.POST.get('target')
        o_note = request.POST.get('note')
        o_expense = request.POST.get('expense', 0)
        
        Order.objects.create(
            o_name = o_name,
            o_count = int(o_number),
            o_order_at = o_date,
            o_unit = o_unit,
            o_target = o_target,
            o_note = o_note,
            o_expense=o_expense
        )

        return redirect('/Order/Inquiry/', {
            'Orders' : Order.objects.all()
        })
    return render(request, 'Main/Order/Order_add_item.html')

# 발주 조회
def readOrders(request):
    try:
        Orders = Order.objects.filter(o_isAcitve=True)
    except Exception as e:
        Orders = None

    return render(request, 'Main/Order/Order_read_items.html',{
        'Orders' : Orders,
    })

class OrderUpdate(UpdateView):
    model = Order
    success_url = "/Order/Inquiry/"
    template_name = "Main/Order/Order_update_item.html"
    fields = '__all__'

    def get_initial(self):
        return super().get_initial()

# 발주 반입처리
def ajaxIncomingOrder(request, pk):
    if request.method == 'POST':
        order = Order.objects.get(pk=pk)
        order.o_status = True
        order.save()

        # 반입 처리가 된다면 재고에 추가
        Stock.objects.create(
            s_name=order.o_name,
            s_count=order.o_count,
            s_unit=order.o_unit,
        )
        
        datas = {
            'message' : '성공적으로 처리 되었습니다.',
        }
        return HttpResponse(json.dumps(datas), content_type="application/json")

    return HttpResponse("실패")

# 발주 삭제
class OrderDelete(DeleteView):
    model = Order
    success_url = "/Order/Inquiry/"
    template_name = "Main/Order/Order_read_items.html"

##### 판매 관리 #####
def sell(request):
    return render(request, 'Main/Sell/main.html', {})

def sellAdmin(request):
    return render(request, 'Main/Sell/sell_menu_admin.html', {'menus' : Menu.objects.all() })

def sell_registerMenu(request):
    if request.method == 'POST':
        print(request.POST.keys(), request.POST.values())
        m_name = request.POST.get('name')
        m_price = request.POST.get('price')
        m_explain = request.POST.get('explain')
        m_pic = request.FILES.get('image')

        Menu.objects.create(m_name=m_name, m_price=m_price, m_explain=m_explain, m_pic=m_pic)
        return redirect('/Sell/Admin/')
    return render(request, 'Main/Sell/sell_menu_register.html')

class SellDelete(DeleteView):
    model = Menu
    success_url = "/Sell/Admin/"

class SellUpdate(UpdateView):
    model = Menu
    success_url = "/Sell/Admin/"
    template_name = "Main/Sell/sell_menu_update.html"
    fields = "__all__"

    def get_initial(self):
        initial = super(UpdateView, self).get_initial()
        return initial


##### 주문 현황 ### 향후 이식
def orderState(request):
    order = Table_order.objects.filter(to_isActive=True).order_by('-to_order_sheet__os_order_date')
    return render(request, 'Main/Order_State/index.html', {'orders' : order})

# 지난 주문
class PastOrder(ListView):
    model = Table_order
    template_name = 'Main/Order_State/Order_past.html'
    context_object_name = 'datas'

    def get_queryset(self):
        return Table_order.objects.filter(to_isActive=False).order_by('-to_order_sheet__os_order_date')
        

# 주문 완료 처리
class orderDone(View):
    def post(self, request, *args, **kwargs):
        order_pk = kwargs.get('pk')
        obj = Table_order.objects.get(pk=order_pk)
        obj.to_status = '완료'
        obj.save(update_fields=['to_status', ])
        return HttpResponse(json.dumps({'status' : '완료', }), content_type="json/application")

# 주문 취소 처리
class orderCancel(View):
    def post(self, request, **kwargs):
        order_pk = kwargs.get('pk')
        obj = Table_order.objects.get(pk=order_pk)
        obj.to_status = '취소'
        obj.to_isActive = False
        obj.save(update_fields=['to_status', 'to_isActive'])
        return HttpResponse(json.dumps({'status' : '취소', }), content_type="json/application")



#### 매출 관리 ####

# 수익 관리
class ProfitMain(View):
    def get(self, request, *args, **kwargs):
        profits = Profit.objects.all().order_by('-p_profit_date')
        amount = profits.aggregate(amount=Sum('p_amount'))
        return render(request, 'Main/Profit/main.html', {'profits' : profits, 'amount' : amount['amount']})

class ProfitSearch(View):
    def post(self, request, *args, **kwargs):
        datas = {}
        start_date = request.POST.get('start-date')
        end_date = request.POST.get('end-date')
        if end_date == "" and start_date == "":
            pass
        elif end_date == "":
            datas = Profit.objects.filter(p_profit_date__year=start_date[:4], \
                p_profit_date__month=start_date[5:7], p_profit_date__day=start_date[8:10] ).order_by('-p_profit_date')
        else:
            datas = Profit.objects.filter(p_profit_date__gte=start_date, p_profit_date__lte=end_date).order_by('-p_profit_date')
        amount = datas.aggregate(amount=Sum('p_amount'))
        return render(request, 'Main/Profit/main.html', {'profits' : datas, 'amount' : amount['amount']})

class ProfitAdd(CreateView):
    model = Profit
    fields = ['p_detail', 'p_amount']
    template_name = 'Main/Profit/Profit_add.html'
    success_url = '/Profit/'
    
    

# 지출 관리
class SpendingMain(View):
    def get(self, request, *args, **kwargs):
        datas = Spending.objects.all().order_by('-s_spending_date')
        amount = datas.aggregate(amount=Sum('s_expense'))
        return render(request, 'Main/Profit/Spending_main.html', {
            'spending' : datas, 
            'amount' : amount
        })

class SpendingAdd(CreateView):
    model = Spending
    fields = ['s_detail', 's_expense']
    template_name = 'Main/Profit/Spending_add.html'
    success_url = '/Spending/'


class SpendingSearch(View):
    def post(self, request, *args, **kwargs):
        datas = {}
        start_date = request.POST.get('start-date')
        end_date = request.POST.get('end-date')
        if end_date == "" and start_date == "":
            pass
        elif end_date == "":
            datas = Spending.objects.filter(s_spending_date__year=start_date[:4], \
                s_spending_date__month=start_date[5:7], s_spending_date__day=start_date[8:10] ).order_by('-s_spending_date')
        else:

Main/templates/Main/Human/hire_main_sign.html
{% extends 'Main/Human/hire_base.html' %}
{% block title %}이력서 작성{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-1"></div>
            <div class="col-md-10">
                <div class="card">
                    <form id="create" action="{% url 'main:HireSign' hire.pk %}" method="POST" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                        <table class="table table-hover">
                            <tr style= "background-color:steelblue">
                                <th style="color:white">이력서 작성</th>
                                <th></th>
                                <th></th>
                            </tr>
                            <tr>
                                <th>지원회사</th>
                                <td><input type="text" id="restaurant_name" name="restaurant_name" class="form-control mb-4" value="{{ hire.restaurant.restaurant_name }}" readonly></td>
                                <td></td>
                            </tr>
                            <tr>
                                <th>성명*</th>
                                <td><input type="text" id="apply_name" name="apply_name" class="form-control mb-4" placeholder="성명을 입력해주세요"></td>
                                <td></td>
                            </tr>
                            <tr>
                                <th>핸드폰*</th>
                                <td><input type="text" id="apply_phone" name="apply_phone" class="form-control mb-4" placeholder="핸드폰번호를 입력해주세요"></td>
                                <td></td>
                            </tr>
                            <tr>
                                <th>이메일</th>
                                <td><input type="text" id="apply_email" name="apply_email" class="form-control mb-4" placeholder="이메일을 입력해주세요"></td>
                                <td></td>
                            </tr>
                            <tr>
                                <th>주소*</th>
                                <td><input type="text" id="apply_address" name="apply_address" class="form-control mb-4" placeholder="주소를 입력해주세요"></td>
                                <td></td>
                            </tr>
                            <tr>
                                <th>최종학력*</th>
                                <td><input type="text" id="apply_academic" name="apply_academic" class="form-control mb-4" placeholder="내용을 입력해주세요"></td>
                                <td></td>
                            </tr>
                            <tr>
                                <th>경력*</th>
                                <td><input type="text" id="apply_career" name="apply_career" class="form-control mb-4" placeholder="내용을 입력해주세요"></td>
                                <td></td>
                            </tr>
                            <tr>
                                <th>지원동기*</th>
                                <td><input type="text" id="apply_motive" name="apply_motive" class="form-control mb-4" placeholder="내용을 입력해주세요"></td>
                                <td></td>
                            </tr>
                            <tr>
                                <th><input type="submit" class="btn btn-outline-primary btn-sm m-0 waves-effect" value="등록"></th>
                                <td></td>
                                <td></td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        <div class="col-md-1"></div>
    </div>
</div>
{% endblock %}

Main/templates/Main/Human/human_education_delete.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<div class="form_box">
    <form action="{% url 'main:EduDelete' education.pk %}" method="POST">
        {% csrf_token %}
        <h1>정말 삭제하시겠습니까?</h1><br>
        <button class="write_button" onclick="button1_click();">네 삭제하겠습니다</button>
    </form>
</div>

<script>
function button1_click() {
  alert("삭제가 성공적으로 완료되었습니다");
}
function button2_click() {
alert("변경이 취소되었습니다");
}
</script>
<style>
    div {
    margin-top:150px; 
    margin-left:-50px; 
    text-align: center;
    }
</style>

Main/templates/Main/Human/human_education_save.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
<div class="container">
<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6">
<br>
<h2>교육내용 수정</h2>
<div class="card">
<form action="{% url 'main:EduSave' education.pk %}" method="POST">
{% csrf_token %}
<table class="table table-hover">
    <tr>
        <th>교육명</th>
        <td><input type="text" id="education_name" name="education_name" class="form-control mb-4" value="{{ education.education_name }}"></td>
    </tr>
    <tr>
        <th>교육내용</th>
        <td><input type="text" id="education_content" name="education_content" class="form-control mb-4" value="{{ education.education_content }}"></td>
    </tr>
    <tr>
        <th>사진</th>
        <td><input type="file" id="education_pic" name="education_pic"></td>
    </tr>
    <tr>
    <th><input type="submit" onclick="button1_click();" class="btn btn-outline-primary btn-sm m-0 waves-effect" value="등록"></a></th>
    </tr>
</table>
</form></div>
</div>
<div class="col-md-3"></div>
</div>
</div>
</div>
<script>
    function button1_click() {
      alert("변경이 성공적으로 완료되었습니다");
    }
</script>
    
<style>
    table {
        float: left;
        border-collapse: collapse;
        text-align: center;
    }
                  
    th {
        font-weight: 100;
        padding: 3px;
        text-align: center;
    }
    
    td {
        padding: 3px;
        text-align: center;
    }

    input {
        text-align: center;
    }
</style>

Main/templates/Main/Human/human_employee_delete.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<div class="form_box">
    <form action="{% url 'main:EmpDelete' employee.pk %}" method="POST">
        {% csrf_token %}
        <h1>정말 삭제하시겠습니까?</h1><br>
        <button class="write_button" onclick="button1_click();">네 삭제하겠습니다</button>
    </form>
</div>

<script>
function button1_click() {
  alert("삭제가 성공적으로 완료되었습니다");
}
function button2_click() {
alert("변경이 취소되었습니다");
}
</script>
<style>
    div {
    margin-top:150px; 
    margin-left:-50px; 
    text-align: center;
    }
</style>

Main/templates/Main/Human/human_employee_inquire.html
{% extends 'Main/Human/human_main.html' %}
{% block title %}인사_사원조회{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
            <div class="col-md-12">
                <h1>전체 사원조회</h1>
                    <table id="searchtable" class='table table-sm table-bordered table-hover'>
                                <thead class="thead-light">                                
                                <tr>
                                    <th>이름</th>
                                    <th>주민등록번호</th>
                                    <th>핸드폰번호</th>
                                    <th>이메일</th>
                                    <th>성별</th>
                                    <th>은행</th>
                                    <th>계좌번호</th>
                                    <th>주소</th>
                                    <th colspan="2">수정∙삭제</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for emp in employee  %}
                                {% if emp.employee_isdelete == False %}
                                <tr>
                                <td>{{ emp.employee_name }}</td>
                                <td>{{ emp.resident_number }}</td>
                                <td>{{ emp.employee_phone }}</td>
                                <td>{{ emp.employee_email }}</td>
                                <td>{{ emp.sex }}</td>  
                                <td>{{ emp.employee_bank }}</td>
                                <td>{{ emp.employee_banknumber }}</td>
                                <td>{{ emp.employee_address }}</td>
                                <td><a href="{% url 'main:EmpSave' emp.pk %}"><button class="btn btn-outline-primary btn-sm m-0 waves-effect">수정</button></a></td>
                                <td><a href="{% url 'main:EmpDelete' emp.pk %}"><button class="btn btn-outline-danger btn-sm m-0 waves-effect">삭제</button></a></td>
                                </tr>
                                {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
            </div>
        <div class="col-md-1"></div>
    </div>
</div>
<style>
        table{
           text-align: center;
        }
        th{
            text-align: center;
        }
   </style>
{% endblock %}   

Main/templates/Main/Human/human_main.html
{% extends 'Main/Based/main.html' %}
{% block title %}인사{% endblock %}

{% block sidebar %}
   {% include 'Main/Human/human_sidebar.html' %}
{% endblock %}

{% block content %}
<h1>안녕하살법</h1>
{% endblock %}

Main/templates/Main/Human/human_work_inquire.html
{% extends 'Main/Human/human_main.html' %}
{% block title %}인사_근무조회{% endblock %}
{% block content %}
<div class="container-fluid">
        <div class="row">
            <div class="col-md-1"></div>
                <div class="col-md-12">
                    <h1>전체 근무조회</h1>
                        <table id="searchtable" class='table table-sm table-bordered table-hover'>
                                    <thead class="thead-light">                                
                                    <tr>
                                        <th>근무자</th>
                                        <th>근무일</th>
                                        <th>근무파트</th>
                                        <th>근무시간</th>
                                        <th colspan="2">수정∙삭제</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for work in work  %}
                                    {% if work.work_isdelete == False %}
                                    <tr>
                                    <td>{{ work.employee.employee_name }}</td>
                                    <td>{{ work.day_work }}</td>
                                    <td>{{ work.work_time }}</td>
                                    <td>{{ work.daytime_work }}</td>
                                    <td><a href="{% url 'main:WorkSave' work.pk %}"><button class="btn btn-outline-primary btn-sm m-0 waves-effect">수정</button></a></td>
                                    <td><a href="{% url 'main:WorkDelete' work.pk %}"><button class="btn btn-outline-danger btn-sm m-0 waves-effect">삭제</button></a></td>
                                    </tr>
                                    {% endif %}
                                    {% endfor %}
                                </tbody>
                            </table>
                            <h4>*근무시간에 휴식시간포함</h4>
                </div>
            <div class="col-md-1"></div>
        </div>
    </div>
    <style>
            table{
               text-align: center;
            }
            th{
                text-align: center;
            }
    </style>
{% endblock %}